In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

import torch
import torch.optim as optim
import torch.nn as nn
from torchviz import make_dot

In [2]:
true_b=1
true_w=2
N=100

# 生成数据
np.random.seed(42)
x=np.random.rand(N,1)
epsilon=(0.1*np.random.rand(N,1))
y=true_b+true_w*x+epsilon

In [3]:
# 乱序索引
idx=np.arange(N)
np.random.shuffle(idx)

# 使用前80个索引作为训练数据索引
train_idx=idx[:int(N*0.8)]
# 使用剩余的20个作为验证数据索引
val_idx=idx[int(N*0.8):]

# 使用刚才的乱序索引来拆分训练数据集和验证数据集
x_train,y_train=x[train_idx],y[train_idx]
x_val,y_val=x[val_idx],y[val_idx]

In [4]:
# 第0步，初始化参数的随机值
np.random.seed(42)
b=np.random.random(1)
w=np.random.random(1)

print(b,w)

[0.37454012] [0.95071431]


In [5]:
# 第1步，计算模型的预测值-使用前向输出
yhat=b+w*x_train

In [7]:
# 第2步 计算损失值
# 我们使用了训练数据集中所有的数据，因此这是一个批量（BATCH）梯度下降方法
# 模型预测的差异就是下面计算的差异

error=(yhat-y_train) # 这里yhat和y_train是两个数组，因此error是差值的数组

# 接下来计算损失值，因为这是一个线性回归，所以我们使用均方差
loss=(error**2).mean()
print(loss)


1.4570419026607908


In [8]:
# 第3步 计算参数b和w的梯度
b_grad=2*error.mean()
w_grad=2*(x_train*error).mean()
print(b_grad,w_grad)

-2.33428293147256 -1.2713249595784388


In [9]:
# 设置学习率
lr=0.1
print(b,w)
# 第4步 使用梯度和学习率来更新参数
b=b-lr*b_grad
w=w-lr*w_grad

print(b,w)

[0.37454012] [0.95071431]
[0.60796841] [1.0778468]


In [2]:
import numpy as np


# 生成数据
true_b=1
true_w=2
N=100

np.random.seed(42)
x=np.random.rand(N,1)
epsilon=(0.1*np.random.rand(N,1))
y=true_b+true_w*x+epsilon
# 乱序索引
idx=np.arange(N)
np.random.shuffle(idx)

# 使用前80个索引作为训练数据索引
train_idx=idx[:int(N*0.8)]
# 使用剩余的20个作为验证数据索引
val_idx=idx[int(N*0.8):]

# 使用刚才的乱序索引来拆分训练数据集和验证数据集
x_train,y_train=x[train_idx],y[train_idx]
x_val,y_val=x[val_idx],y[val_idx]


# 第0步：给b和w设置随机初始化值
np.random.seed(42)
b=np.random.randn(1)
w=np.random.randn(1)
print(b,w)

# 设置学习率
lr=0.1
# 定义迭代的周期
n_epochs=1000

for epoch in range(n_epochs):
    #第1步：计算模型的预测值-使用前向传输
    yhat=b+w*x_train
    #第2步：计算损失值。
    #我们使用了所有的训练数据，所以这是一个批量梯度下降。
    #这里我们计算模型预测和实际值的差异
    error=(yhat-y_train)
    #这是一个回归函数，所以我们使用均方差来计算损失值
    loss=(error**2).mean()
    #第3步：计算b和w的梯度
    b_grad=2*error.mean()
    w_grad=2*(x_train*error).mean()
    
    #第4步：使用梯度和学习率来更新参数
    b=b-lr*b_grad
    w=w-lr*w_grad

print(b,w)
    
    



[0.49671415] [-0.1382643]
[1.05303414] [1.99581323]


In [3]:
from sklearn.linear_model import LinearRegression
#使用ScikitLearn的线性回归模型来验证我们的梯度下降效果
linr=LinearRegression()
linr.fit(x_train,y_train)
print(linr.intercept_,linr.coef_[0])

[1.05303354] [1.99581441]


In [4]:
import torch
# 生成一个值为3.14159的标量
scalar=torch.tensor(3.14159)
# 生成一个数组向量
vector=torch.tensor([1,2,3])
# 生成一个2*3的矩阵，用1填充，类型是float
matrix=torch.ones((2,3),dtype=torch.float)
# 生成一个2*3*4的三维数组，即张量，用随机数填充，类型是float
tensor=torch.randn((2,3,4),dtype=torch.float)

print(scalar)
print(vector)
print(matrix)
print(tensor)

tensor(3.1416)
tensor([1, 2, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[[ 1.2059,  1.3801,  1.3065,  0.4145],
         [ 0.2110,  0.8104,  0.0538,  1.8037],
         [ 0.3963,  0.3585,  0.7340,  0.5113]],

        [[-0.7215,  2.2712,  0.0635, -0.8904],
         [-0.6842, -0.7252,  0.5084,  0.4782],
         [ 1.1503, -1.1160,  0.6587, -0.3119]]])


In [5]:
print(tensor.size(),tensor.shape)

torch.Size([2, 3, 4]) torch.Size([2, 3, 4])


In [6]:
print(scalar.size(),scalar.shape)

torch.Size([]) torch.Size([])


In [7]:
matrix=torch.ones((2,3),dtype=torch.float)
#我们把原来的张量的形状做了改变，但是改变后的张量和原来的是一样的
same_matrix=matrix.view(1,6)
# 如果我们修改了张量中的某个元素的值
same_matrix[0,2]=2
# matrix和same_matrix的元素值都会改变
print(matrix)
print(same_matrix)

tensor([[1., 1., 2.],
        [1., 1., 1.]])
tensor([[1., 1., 2., 1., 1., 1.]])


In [8]:
# 我们可以使用new_tensor()方法来创建一个新的张量
different_matrix=matrix.new_tensor(matrix.view(1,6))
# 现在，如果我们修改新的张量的值
different_matrix[0,1]=3
# 原有的张量的值不会受到影响，但是我们会看到pytorch的警告信息
# 它提示我们使用clone()方法
print(matrix)
print(different_matrix)

tensor([[1., 1., 2.],
        [1., 1., 1.]])
tensor([[1., 3., 2., 1., 1., 1.]])


C:\Users\liuyi\AppData\Local\Temp\ipykernel_18580\474334958.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than tensor.new_tensor(sourceTensor).
  different_matrix=matrix.new_tensor(matrix.view(1,6))


In [9]:
another_matrix=matrix.view(1,6).clone().detach()
another_matrix[0,1]=4.
print(matrix)
print(another_matrix)

tensor([[1., 1., 2.],
        [1., 1., 1.]])
tensor([[1., 4., 2., 1., 1., 1.]])


In [10]:
x_train_tensor=torch.as_tensor(x_train)
x_train.dtype,x_train_tensor.dtype

(dtype('float64'), torch.float64)

In [11]:
float_tensor=x_train_tensor.float()
float_tensor.dtype

torch.float32

In [12]:
dummy_array=np.array([1,2,3])
dummy_tensor=torch.as_tensor(dummy_array)
# 修改numpy数组的元素值
dummy_array[1]=0
# 张量内的元素值也会被修改
dummy_tensor

tensor([1, 0, 3], dtype=torch.int32)

In [13]:
dummy_tensor.numpy()

array([1, 0, 3])

In [16]:
device='cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [17]:
n_cudas=torch.cuda.device_count()
for i in range(n_cudas):
    print(torch.cuda.get_device_name())

In [18]:
gup_tensor=torch.as_tensor(x_train).to(device)
gup_tensor[0]

tensor([0.5227], dtype=torch.float64)

In [19]:
device='cuda' if torch.cuda.is_available() else 'cpu'
x_train_tensor=torch.as_tensor(x_train).to(device)
y_train_tensor=torch.as_tensor(y_train).to(device)

In [20]:
print(type(x_train),type(x_train_tensor),x_train_tensor.type())

<class 'numpy.ndarray'> <class 'torch.Tensor'> torch.DoubleTensor


In [21]:
back_to_numpy=x_train_tensor.cpu().numpy()